# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606a2f76e26a4d29a14d60581e2aae3d11ad1e8fa83750713121ca8d380096430ca63099d6e8a70642f5380f27c031acbe5f635ba48bc1a04d9a4ad8185973c3

test:
  secret_key_base: 7bb62a81207e034684a45a40b0d62be546b9d64e29a70f6fad9c0cf4de4289b5f324eaed6c28f24cf1e0d10104455a103c1e5bcaf2a0e61345688d80be4e9e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
